spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: order-user
    password: order-password
    url: r2dbc:postgresql://localhost:5433/order_db
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway: # flyway doesn't have support for R2DBC, so we will use JDBC here
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5433/order_db
  webflux:
    base-path: /${app.api.version}

server:
  port: 9002
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

app:
  api:
    version: 20250525

polar:
  catalog-service-url: "http://localhost:9001/20250525"