spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: order-user
    password: order-password
    url: r2dbc:postgresql://localhost:5432/order_db
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10

server:
  port: 9002
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful